#####################################################################################
#                                                                                   #
# Copyright (c) 2024, Shenyang Institute of Automation, Chinese Academy of Sciences #
#                                                                                   #
# Authors: Yanpeng Jia                                                              #
# Contact: jiayanpeng@sia.cn                                                        #
#                                                                                   #
#####################################################################################

trlo:

  odomNode:

    initialPose:
      use: true
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        w: 1.0
        x: 0.0
        y: 0.0
        z: 0.0

    preprocessing:
      cropBoxFilter:
        use: false
        size: 1.0
      voxelFilter:
        scan:
          use: false
          res: 0.25
        submap:
          use: true
          res: 0.5

    keyframe:
      threshD: 5.0
      threshR: 45.0

    submap:
      keyframe:
        knn: 10
        kcv: 10
        kcc: 10

    imu:
      calibTime: 3
      bufferSize: 2000
    
    box:
      bufferSize: 3

    groundL:
      threshold: 0.2

    gicp:
      minNumPoints: 10
      s2s:
        kCorrespondences: 10
        maxCorrespondenceDistance: 1.0
        maxIterations: 32
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
      s2m:
        kCorrespondences: 20
        maxCorrespondenceDistance: 0.5
        maxIterations: 32
        transformationEpsilon: 0.01
        euclideanFitnessEpsilon: 0.01
        ransac:
          iterations: 5
          outlierRejectionThresh: 1.0
